---
- name: Install libgmp
  apt: pkg=libgmp3c2 

- name: Install build-essential
  apt: pkg=build-essential
 
- name: Install haskell-platform
  apt: pkg=haskell-platform
 
- name: Get GHC
  get_url: dest=/tmp url=http://www.haskell.org/ghc/dist/7.6.3/ghc-7.6.3-x86_64-unknown-linux.tar.bz2
  sudo: false
 
- name: Untar GHC
  command: chdir=/tmp tar -xvf ghc-7.6.3-x86_64-unknown-linux.tar.bz2
  sudo: false
 
- name: Configure GHC
  command: chdir=/tmp/ghc-7.6.3 ./configure
  sudo: false
 
- name: Make and install GHC
  command: chdir=/tmp/ghc-7.6.3 make install
 
- name: Update cabal
  command: cabal update
  sudo: false
 
- name: Install cabal
  command: cabal install cabal cabal-install
  sudo: false
 
- name: Link cabal
  file: src=~/.cabal/bin/cabal dest=/usr/local/bin/cabal state=link
